_target_: deepaudio.tts.datamodules.wavernn_datamodule.WaveRNNDataModule
train_metadata: ???
dev_metadata: ???
batch_max_steps: ???
n_shift: ???
mode: ???
bits: ???
batch_size: 128
num_workers: 0
pin_memory: False
